[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0 ]

[opener]
archive = [
	{ run = '7z x "$1"', desc = "Extract here", for = "linux" },
]
text = [
	{ run = 'nvim "$1"', block = true, desc = "Edit", for = "linux" },
]
image = [
	{ run = 'imv "$1"', desc = "View", for = "linux" },
]
video = [
	{ run = 'mpv "$1"', desc = "Play", for = "linux" },
]
audio = [
	{ run = 'mpv "$1"', desc = "Play", for = "linux" },
]
pdf = [
	{ run = 'zathura "$1"', desc = "View PDF", for = "linux" },
]
office = [
	{ run = 'libreoffice "$1"', desc = "Edit", for = "linux" },
]
web = [
	{ run = 'firefox "$1"', desc = "Open in Firefox", for = "linux" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "text/*",  use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "application/zip",             use = [ "extract", "reveal" ] },
	{ mime = "application/gzip",            use = [ "extract", "reveal" ] },
	{ mime = "application/x-tar",           use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip",          use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip2",         use = [ "extract", "reveal" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
	{ mime = "application/x-rar",           use = [ "extract", "reveal" ] },
	{ mime = "application/xz",              use = [ "extract", "reveal" ] },

	{ mime = "application/pdf", use = [ "open", "reveal" ] },
	{ mime = "text/html", use = [ "open", "edit", "reveal" ] },

	{ name = "*", use = [ "open", "reveal" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]

preloaders = [
	{ name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
]
previewers = [
	{ name = "*/", run = "folder", sync = true },
	{ mime = "text/*", run = "code" },
	{ mime = "*/xml", run = "code" },
	{ mime = "*/javascript", run = "code" },
	{ mime = "*/x-wine-extension-ini", run = "code" },

	# Archive
	{ mime = "application/*zip", run = "archive" },
	{ mime = "application/x-tar", run = "archive" },
	{ mime = "application/x-bzip2", run = "archive" },
	{ mime = "application/x-7z-compressed", run = "archive" },
	{ mime = "application/x-rar", run = "archive" },
	{ mime = "application/x-xz", run = "archive" },

	# Image
	{ mime = "image/*", run = "image" },

	# Video
	{ mime = "video/*", run = "video" },

	# PDF
	{ mime = "application/pdf", run = "pdf" },

	# JSON
	{ mime = "application/json", run = "json" },

	# Font
	{ mime = "font/*", run = "font" },
	{ mime = "application/vnd.ms-opentype", run = "font" },
]

[input]
cursor_blink = false

# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [ 0, 2 ]

# create
create_title  = "Create:"
create_origin = "top-center"
create_offset = [ 0, 2 ]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [ 0, 1 ]

# trash
trash_title 	= "Move {n} selected file{s} to trash? (y/N)"
trash_origin	= "top-center"
trash_offset	= [ 0, 2 ]

# delete
delete_title 	= "Delete {n} selected file{s} permanently? (y/N)"
delete_origin	= "top-center"
delete_offset	= [ 0, 2 ]

[select]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [ 0, 1 ]

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false

[log]
enabled = false
