# Starship configuration with gruvbox theme

format = """
[](#3c3836)\
$os\
$username\
[](bg:#504945 fg:#3c3836)\
$directory\
[](fg:#504945 bg:#665c54)\
$git_branch\
$git_status\
[](fg:#665c54 bg:#928374)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:#928374 bg:#a89984)\
$time\
[ ](fg:#a89984)\
$line_break$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# OS module
[os]
style = "bg:#3c3836 fg:#ebdbb2"
disabled = false

# Username module
[username]
show_always = true
style_user = "bg:#3c3836 fg:#ebdbb2"
style_root = "bg:#3c3836 fg:#fb4934"
format = '[$user ]($style)'
disabled = false

# Directory module
[directory]
style = "fg:#282828 bg:#504945"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Git branch module
[git_branch]
symbol = ""
style = "bg:#665c54"
format = '[[ $symbol $branch ](fg:#282828 bg:#665c54)]($style)'

# Git status module
[git_status]
style = "bg:#665c54"
format = '[[($all_status$ahead_behind )](fg:#282828 bg:#665c54)]($style)'

# Node.js module
[nodejs]
symbol = ""
style = "bg:#928374"
format = '[[ $symbol ($version) ](fg:#282828 bg:#928374)]($style)'

# Rust module
[rust]
symbol = ""
style = "bg:#928374"
format = '[[ $symbol ($version) ](fg:#282828 bg:#928374)]($style)'

# Golang module
[golang]
symbol = ""
style = "bg:#928374"
format = '[[ $symbol ($version) ](fg:#282828 bg:#928374)]($style)'

# PHP module
[php]
symbol = ""
style = "bg:#928374"
format = '[[ $symbol ($version) ](fg:#282828 bg:#928374)]($style)'

# Python module
[python]
symbol = ""
style = "bg:#928374"
format = '[[ $symbol ($version) ](fg:#282828 bg:#928374)]($style)'

# Time module
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#a89984"
format = '[[  $time ](fg:#282828 bg:#a89984)]($style)'

# Character module (prompt symbol)
[character]
success_symbol = '[❯](bold #b8bb26)'
error_symbol = '[❯](bold #fb4934)'
vimcmd_symbol = '[❮](bold #d79921)'

# Command duration module
[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bg:#928374"
format = '[[ took $duration ](fg:#282828 bg:#928374)]($style)'

# Memory usage module
[memory_usage]
disabled = true
threshold = -1
symbol = "󰍛 "
style = "bg:#928374"
format = '[[ $symbol ${ram}( | ${swap}) ](fg:#282828 bg:#928374)]($style)'

# Battery module
[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 10
style = "bold #fb4934"

[[battery.display]]
threshold = 30
style = "bold #fabd2f"

# Package module
[package]
symbol = "󰏗 "
style = "bg:#928374"
format = '[[ $symbol $version ](fg:#282828 bg:#928374)]($style)'

# Docker module
[docker_context]
symbol = " "
style = "bg:#928374"
format = '[[ $symbol $context ](fg:#282828 bg:#928374)]($style)'

# Status module
[status]
style = "bg:#fb4934"
symbol = "🔴"
success_symbol = "🟢"
format = '[[ $symbol $common_meaning$signal_name$maybe_int ](fg:#282828 bg:#fb4934)]($style)'
map_symbol = true
disabled = false

# Shell module
[shell]
fish_indicator = "󰈺 "
bash_indicator = " "
zsh_indicator = " "
style = "bg:#3c3836 fg:#ebdbb2"
disabled = false
